---
sdwan_acl: sdwan-acl
sdwan_hsrp_priority: "{{ 90 if vlan_id | int % 2 == 0 else 100 }}"

acme:
  ip_addr_and_mask: "10.{{ fi_octet }}.10.2 255.255.255.248"
  vip_addr: "10.{{ fi_octet }}.10.1"

evilcorp:
  ip_addr_and_mask: "10.{{ fi_octet }}.20.2 255.255.255.0"
  vip_addr: "10.{{ fi_octet }}.20.1"