---
sdwan_acl: sdwan-acl
sdwan_hsrp_priority: "{{ 100 if vlan_id | int % 2 == 0 else 90 }}"

att_ip_addr_and_mask: "10.{{ fi_octet }}.10.3 255.255.255.248"
att_vip_addr: "10.{{ fi_octet }}.10.1"

comcast_ip_addr_and_mask: "10.{{ fi_octet }}.20.3 255.255.255.0"
comcast_vip_addr: "10.{{ fi_octet }}.20.1"